// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdsxfjqrcmxqbshdkobz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkc3hmanFyY214cWJzaGRrb2J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTY0MTcsImV4cCI6MjA2NDc5MjQxN30.GpbBJMz3qhQkTEhPd7lnsTR9N8262tg9Yrgz5zvuBHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);